# Generated by Django 4.2.5 on 2024-02-10 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[("CREATE SCHEMA IF NOT EXISTS content;")],
            reverse_sql=[("DROP SCHEMA IF EXISTS content CASCADE;")],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('creation_date', models.DateField(blank=True, verbose_name='creation_date')),
                ('activity_type', models.CharField(choices=[('scientific', 'Scientific'), ('educational', 'Educational'), ('production', 'Production'), ('experimental', 'Experimental')], max_length=128, verbose_name='activity_type')),
            ],
            options={
                'verbose_name': 'laboratory',
                'verbose_name_plural': 'laboratories',
                'db_table': 'content"."laboratory',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'db_table': 'content"."publication',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='fullname')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonLaboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField(verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory', verbose_name='laboratory')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'person_laboratory',
                'verbose_name_plural': 'person_laboratories',
                'db_table': 'content"."person_laboratory',
            },
        ),
        migrations.CreateModel(
            name='PublicationLaboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory', verbose_name='laboratory')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.publication', verbose_name='publication')),
            ],
            options={
                'verbose_name': 'publication_laboratory',
                'verbose_name_plural': 'publication_laboratories',
                'db_table': 'content"."publication_laboratory',
            },
        ),
        migrations.AddField(
            model_name='laboratory',
            name='publications',
            field=models.ManyToManyField(through='laboratories.PublicationLaboratory', to='laboratories.publication'),
        ),
    ]
