# Generated by Django 4.2.5 on 2024-02-10 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=[("CREATE SCHEMA IF NOT EXISTS content;")],
            reverse_sql=[("DROP SCHEMA IF EXISTS content CASCADE;")],
        ),
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('creation_date', models.DateField(blank=True, verbose_name='creation_date')),
                ('file_path', models.TextField(blank=True, verbose_name='file_path')),
                ('rating', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)], verbose_name='rating')),
                ('type', models.CharField(choices=[('movie', 'movie'), ('tv_show', 'tv_show')], max_length=128, verbose_name='type')),
            ],
            options={
                'verbose_name': 'film_work',
                'verbose_name_plural': 'film_works',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'db_table': 'content"."publication',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='fullname')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField(verbose_name='role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.filmwork', verbose_name='film_work')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'person_film_work',
                'verbose_name_plural': 'person_film_works',
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.CreateModel(
            name='PublicationFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.filmwork', verbose_name='film_work')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.publication', verbose_name='person')),
            ],
            options={
                'verbose_name': 'publication_film_work',
                'verbose_name_plural': 'publication_film_works',
                'db_table': 'content"."publication_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='publications',
            field=models.ManyToManyField(through='laboratories.PublicationFilmwork', to='laboratories.publication'),
        ),
    ]
