# Generated by Django 4.2.5 on 2024-02-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(through='laboratories.PersonFilmwork', to='laboratories.person'),
        ),
    ]
