# Generated by Django 4.2.5 on 2024-02-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_laboratory_persons'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicationlaboratory',
            unique_together={('publication', 'laboratory')},
        ),
        migrations.AlterUniqueTogether(
            name='personlaboratory',
            unique_together={('laboratory', 'person', 'role')},
        ),
    ]
