# Generated by Django 4.2.5 on 2024-02-26 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0003_alter_publicationlaboratory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='publications',
            field=models.ManyToManyField(null=True, through='laboratories.PublicationLaboratory', to='laboratories.publication'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='persons',
            field=models.ManyToManyField(null=True, through='laboratories.PersonLaboratory', to='laboratories.person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='personlaboratory',
            name='role',
            field=models.CharField(choices=[('head', 'Head'), ('staff', 'Staff'), ('intern', 'Intern')], max_length=20, verbose_name='role'),
        ),
    ]
