# Generated by Django 4.2.5 on 2024-05-22 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0007_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Created at'),
        ),
    ]
