# Generated by Django 4.2.5 on 2024-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0008_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(default='me', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
