# Generated by Django 4.2.5 on 2024-05-23 10:42

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratories", "0009_news_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/person_photos/",
                verbose_name="photo",
            ),
        ),
    ]
