# Generated by Django 4.2.5 on 2024-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratories", "0010_person_description_person_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboratory",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/laboratory_photos/",
                verbose_name="photo",
            ),
        ),
    ]
