# Generated by Django 4.2.5 on 2024-05-30 19:44

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratories", "0011_laboratory_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
    ]
