# Generated by Django 4.2.5 on 2024-05-30 20:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratories", "0012_alter_publication_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboratory",
            name="description",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=markdownx.models.MarkdownxField(
                blank=True, null=True, verbose_name="content"
            ),
        ),
    ]
