# Generated by Django 4.2.5 on 2024-05-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratories", "0013_alter_laboratory_description_alter_news_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="publication_date"
            ),
        ),
    ]
