openapi: 3.0.0
info:
  title: Laboratories ListApi
  version: v1
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/v1/laboratories/:
    get:
      description: ""
      parameters:
        - name: page
          in: query
          description: Номер страницы
          required: false
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Количество объектов
                    example: 1000
                  total_pages:
                    type: integer
                    description: Количество страниц
                    example: 20
                  prev:
                    type: integer
                    nullable: true
                    description: Номер предыдущей страницы
                    example: 1
                  next:
                    type: integer
                    nullable: true
                    description: Номер следующей страницы
                    example: 2
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/Laboratory"
  
  /api/v1/laboratories/{id}:
    get:
      description: ""
      parameters:
        - in: path
          name: id  
          required: true
          schema:
            type: string
            format: uuid
          description: ID Лаборатории
        
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Laboratory"
components:
  schemas:
    Laboratory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID 
        title:
          type: string
          description: Название 
          example: Crescent Star
        description:
          type: string
          description: Описание  
          example: In 1944, the Germans began rounding up the Jews of Rhodes.
        creation_date:
          type: string
          format: date
          description: Дата создания
        activity_type:
          type: string
          description: Тип
          example: scientific
        publications:
          type: array
          description: Список публикаций
          example: [Drama, Short]
          items:
            type: string
            description: Название публикации
        head:
          type: array
          description: Список заведующих
          example: [Darrell Geer, Michael Bond]
          items:
            type: string
            description: Имя заведующего
        intern:
          type: array
          description: Список стажеров
          example: [Turgut Turk Adiguzel]
          items:
            type: string
            description: Имя стажера
            example: Turgut Turk Adiguzel
        staff:
          type: array
          description: Список сотрудников
          example: [Turgut Turk Adiguzel]
          items:
            type: string
            description: Имя сотрудника
            example: Turgut Turk Adiguzel                
